using Modules.Shared.Application.Messaging;
namespace HR.Application.Employees.CreateFullEmployee
{
    public sealed record CreateFullEmployeeCommand(
        // 1. Personal Information
        string FirstName,
        string FatherName,
        string LastName,
        string NationalId,
        DateTime DateOfBirth,
        string Gender,
        string Phone,
        string Email,
        string MaritalStatus,
        string Address,
        bool IsDisabled, // فئة خاصة

        // 2. Job Information
        Guid? OrgUnitId, // الإدارة التابع لها
        string JobTitleName, // المسمى الوظيفي (Text input in UI)
        Guid JobTitleId,
        string QualificationName, // المؤهل الدراسي (Text input in UI)
        Guid? JobGradeId, // الدرجة المالية
        DateTime HireDate, // تاريخ التعيين
        DateTime? JobGradeDate, // تاريخ الحصول على الدرجة
        Guid? EmploymentTypeId, // نوع التعيين

        // 3. E-Files (Paths generated by Controller)
        string ProfileImagePath,
        string NationalIdCardPath,
        string QualificationFilePath,
        string BirthCertificatePath,
        string MilitaryFilePath,
        string ContractFilePath,
        string PoliceClearancePath, // الفيش

        // 4. Financial Information
        decimal? BasicSalary2019,
        decimal? GrossSalary,
        string InsuranceNumber,
        string BankName,
        string BankAccountNumber,
        bool HasFellowshipFund, // صندوق الزمالة
        bool HasMedicalFund // التكافل
    ) : ICommand<Guid>;
}