using Microsoft.AspNetCore.Http;
using Modules.Shared.Application.Messaging;
namespace HR.Application.Employees.CreateFullEmployee
{
    public sealed record CreateFullEmployeeCommand(
        // 1. Personal Information
        string FirstName,
        string FatherName,
        string LastName,
        string NationalId,
        DateTime DateOfBirth,
        string Gender,
        string Phone,
        string Email,
        string MaritalStatus,
        string Address,
        bool IsDisabled, // فئة خاصة

        // 2. Job Information
        Guid? OrgUnitId, // الإدارة التابع لها
        Guid JobTitleId,
        Guid? JobGradeId, // الدرجة المالية
        DateTime HireDate, // تاريخ التعيين
        DateTime? JobGradeDate, // تاريخ الحصول على الدرجة
        Guid? EmploymentTypeId, // نوع التعيين
        Guid? FunctionalGroupId,

        // 3. E-Files (Paths generated by Controller)
        IFormFile? ProfileImagePath,
        IFormFile? NationalIdCardFrontPath,
        IFormFile? NationalIdCardBackPath,
        IFormFile? QualificationFilePath,
        IFormFile? BirthCertificatePath,
        IFormFile? MilitaryFilePath,
        IFormFile? ContractFilePath,
        IFormFile? PoliceClearancePath, // الفيش
        IFormFile? MarriageDocumentPath,

        // 4. Financial Information
        decimal? BasicSalary2019,
        decimal? GrossSalary,
        decimal? Incentives,
        string InsuranceNumber,
        string BankName,
        string BankAccountNumber,
        bool HasFellowshipFund, // صندوق الزمالة
        bool HasMedicalFund, // التكافل

        // 5. Employee Qualification
        Guid QualificationTypeId,
        string QualificationFullName,
        string Specialization,
        string University,
        int? GraduationYear,
        string Grade,
        DateTime? QualificationValidFrom,
        DateTime? QualificationValidTo,
        string QualificationNotes
        ) : ICommand<Guid>;
}