// <auto-generated />
using System;
using Geography.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Geography.Infrastructure.Migrations
{
    [DbContext(typeof(GeographyDbContext))]
    [Migration("20260428220304_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Geopraphy")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Geography.Domain.CityCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GovernorateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("Name");

                    b.ToTable("CityCenters", "Geopraphy");
                });

            modelBuilder.Entity("Geography.Domain.Governorate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Governorates", "Geopraphy");
                });

            modelBuilder.Entity("Geography.Domain.LocalUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CityCenterId");

                    b.HasIndex("Name");

                    b.ToTable("LocalUnits", "Geopraphy");
                });

            modelBuilder.Entity("Geography.Domain.Village", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CityCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocalUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CityCenterId");

                    b.HasIndex("LocalUnitId");

                    b.HasIndex("Name");

                    b.ToTable("Villages", "Geopraphy");
                });

            modelBuilder.Entity("Geography.Domain.CityCenter", b =>
                {
                    b.HasOne("Geography.Domain.Governorate", "Governorate")
                        .WithMany("CityCenters")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("Geography.Domain.LocalUnit", b =>
                {
                    b.HasOne("Geography.Domain.CityCenter", "CityCenter")
                        .WithMany("LocalUnits")
                        .HasForeignKey("CityCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CityCenter");
                });

            modelBuilder.Entity("Geography.Domain.Village", b =>
                {
                    b.HasOne("Geography.Domain.CityCenter", null)
                        .WithMany("Villages")
                        .HasForeignKey("CityCenterId");

                    b.HasOne("Geography.Domain.LocalUnit", "LocalUnit")
                        .WithMany("Villages")
                        .HasForeignKey("LocalUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalUnit");
                });

            modelBuilder.Entity("Geography.Domain.CityCenter", b =>
                {
                    b.Navigation("LocalUnits");

                    b.Navigation("Villages");
                });

            modelBuilder.Entity("Geography.Domain.Governorate", b =>
                {
                    b.Navigation("CityCenters");
                });

            modelBuilder.Entity("Geography.Domain.LocalUnit", b =>
                {
                    b.Navigation("Villages");
                });
#pragma warning restore 612, 618
        }
    }
}
