// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Organization.Infrastructure.Database;

#nullable disable

namespace Organization.Infrastructure.Migrations
{
    [DbContext(typeof(OrganizationDbContext))]
    partial class OrganizationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Organization")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Geography.Domain.CityCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GovernorateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId");

                    b.ToTable("CityCenter", "Organization");
                });

            modelBuilder.Entity("Geography.Domain.Governorate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Governorate", "Organization");
                });

            modelBuilder.Entity("Geography.Domain.LocalUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityCenterId");

                    b.ToTable("LocalUnit", "Organization");
                });

            modelBuilder.Entity("Geography.Domain.Village", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CityCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocalUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityCenterId");

                    b.HasIndex("LocalUnitId");

                    b.ToTable("Village", "Organization");
                });

            modelBuilder.Entity("Organization.Domain.FunctionalGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("QualitativeGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("QualitativeGroupId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QualitativeGroupId");

                    b.HasIndex("QualitativeGroupId1");

                    b.ToTable("FunctionalGroups", "Organization");
                });

            modelBuilder.Entity("Organization.Domain.JobGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GradeLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("YearsNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("JobGrades", "Organization");
                });

            modelBuilder.Entity("Organization.Domain.JobTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("FunctionalGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FunctionalGroupId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FunctionalGroupId");

                    b.HasIndex("FunctionalGroupId1");

                    b.ToTable("JobTitles", "Organization");
                });

            modelBuilder.Entity("Organization.Domain.LeadershipPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobTitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrgUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrgUnitId");

                    b.ToTable("LeadershipPositions", "Organization");
                });

            modelBuilder.Entity("Organization.Domain.LeadershipPositionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisionNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LeadershipPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeadershipPositionId");

                    b.ToTable("LeadershipPositionHistories", "Organization");
                });

            modelBuilder.Entity("Organization.Domain.OrgUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("GovernorateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrgUnitTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrgUnitTypeId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("GovernorateId");

                    b.HasIndex("Name");

                    b.HasIndex("OrgUnitTypeId");

                    b.HasIndex("OrgUnitTypeId1");

                    b.HasIndex("ParentId");

                    b.ToTable("OrgUnits", "Organization");
                });

            modelBuilder.Entity("Organization.Domain.OrgUnitType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanHaveChild")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LevelOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("OrgUnitTypes", "Organization");
                });

            modelBuilder.Entity("Organization.Domain.QualitativeGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("QualitativeGroups", "Organization");
                });

            modelBuilder.Entity("Geography.Domain.CityCenter", b =>
                {
                    b.HasOne("Geography.Domain.Governorate", "Governorate")
                        .WithMany("CityCenters")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("Geography.Domain.LocalUnit", b =>
                {
                    b.HasOne("Geography.Domain.CityCenter", "CityCenter")
                        .WithMany("LocalUnits")
                        .HasForeignKey("CityCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CityCenter");
                });

            modelBuilder.Entity("Geography.Domain.Village", b =>
                {
                    b.HasOne("Geography.Domain.CityCenter", null)
                        .WithMany("Villages")
                        .HasForeignKey("CityCenterId");

                    b.HasOne("Geography.Domain.LocalUnit", "LocalUnit")
                        .WithMany("Villages")
                        .HasForeignKey("LocalUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalUnit");
                });

            modelBuilder.Entity("Organization.Domain.FunctionalGroup", b =>
                {
                    b.HasOne("Organization.Domain.QualitativeGroup", "QualitativeGroup")
                        .WithMany()
                        .HasForeignKey("QualitativeGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Organization.Domain.QualitativeGroup", null)
                        .WithMany("FunctionalGroups")
                        .HasForeignKey("QualitativeGroupId1");

                    b.Navigation("QualitativeGroup");
                });

            modelBuilder.Entity("Organization.Domain.JobTitle", b =>
                {
                    b.HasOne("Organization.Domain.FunctionalGroup", "FunctionalGroup")
                        .WithMany()
                        .HasForeignKey("FunctionalGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Organization.Domain.FunctionalGroup", null)
                        .WithMany("JobTitles")
                        .HasForeignKey("FunctionalGroupId1");

                    b.Navigation("FunctionalGroup");
                });

            modelBuilder.Entity("Organization.Domain.LeadershipPosition", b =>
                {
                    b.HasOne("Organization.Domain.OrgUnit", "OrgUnit")
                        .WithMany()
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrgUnit");
                });

            modelBuilder.Entity("Organization.Domain.LeadershipPositionHistory", b =>
                {
                    b.HasOne("Organization.Domain.LeadershipPosition", "LeadershipPosition")
                        .WithMany()
                        .HasForeignKey("LeadershipPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeadershipPosition");
                });

            modelBuilder.Entity("Organization.Domain.OrgUnit", b =>
                {
                    b.HasOne("Geography.Domain.Governorate", "Governorate")
                        .WithMany()
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Organization.Domain.OrgUnitType", "OrgUnitType")
                        .WithMany()
                        .HasForeignKey("OrgUnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Organization.Domain.OrgUnitType", null)
                        .WithMany("OrgUnits")
                        .HasForeignKey("OrgUnitTypeId1");

                    b.HasOne("Organization.Domain.OrgUnit", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Governorate");

                    b.Navigation("OrgUnitType");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Geography.Domain.CityCenter", b =>
                {
                    b.Navigation("LocalUnits");

                    b.Navigation("Villages");
                });

            modelBuilder.Entity("Geography.Domain.Governorate", b =>
                {
                    b.Navigation("CityCenters");
                });

            modelBuilder.Entity("Geography.Domain.LocalUnit", b =>
                {
                    b.Navigation("Villages");
                });

            modelBuilder.Entity("Organization.Domain.FunctionalGroup", b =>
                {
                    b.Navigation("JobTitles");
                });

            modelBuilder.Entity("Organization.Domain.OrgUnit", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Organization.Domain.OrgUnitType", b =>
                {
                    b.Navigation("OrgUnits");
                });

            modelBuilder.Entity("Organization.Domain.QualitativeGroup", b =>
                {
                    b.Navigation("FunctionalGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
